# Generated by Django 4.1 on 2022-08-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('age', models.CharField(max_length=40)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1, null=True)),
                ('note', models.TextField()),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
